// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-nostr/nostr/internal/web"
	"io/fs"
	"net/http"
)

// Injectors from wire.go:

func buildHTTPServer() *http.Server {
	handler := provideFileServerHandler()
	server := &http.Server{
		Handler: handler,
	}
	return server
}

// wire.go:

func provideFileServerHandler() http.Handler {
	dist, _ := fs.Sub(web.FS, "dist")
	return http.FileServer(http.FS(dist))
}
