// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
	"github.com/go-nostr/nostr"
	"github.com/go-nostr/nostr/internal/web"
	"io/fs"
	"net/http"
)

// Injectors from wire.go:

func buildClientServer() *http.Server {
	string2 := provideClientAddr()
	handler := provideClientHandler()
	server := &http.Server{
		Addr:    string2,
		Handler: handler,
	}
	return server
}

func buildRelayServer() *http.Server {
	string2 := provideRelayAddr()
	handler := provideRelayHandler()
	server := &http.Server{
		Addr:    string2,
		Handler: handler,
	}
	return server
}

// wire.go:

const (
	defaultHostname   = "0.0.0.0"
	defaultClientPort = 4200
	defaultRelayPort  = 3001
)

func provideClientAddr() string {
	return fmt.Sprintf("%v:%v", defaultHostname, defaultClientPort)
}

func provideRelayAddr() string {
	return fmt.Sprintf("%v:%v", defaultHostname, defaultRelayPort)
}

func provideClientHandler() http.Handler {
	dist, err := fs.Sub(web.FS, "dist")
	if err != nil {
		fmt.Printf("Error: %v", err)
		return nil
	}
	return http.FileServer(http.FS(dist))
}

func provideRelayHandler() http.Handler {
	return nostr.NewRelay()
}
