name: Angular
on:
  push:
jobs:
  client:
    name: Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
      - name: Install NPM dependencies
        run: npm ci
      - name: Build Angular application
        run: npm run build -w internal/client
      - name: Run Angular tests
        run: npm run test -w internal/client --watch=false --browsers=ChromeHeadless
      - name: Run Angular linter
        run: npm run lint -w internal/client
      # TODO: change name of artifact
      - name: Tar files
        run: tar -cvf dist.tar internal/client/dist
      - name: Upload Angular build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist.tar