name: Go
on:
  push:
jobs:
  cmd:
    name: CMD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
      - name: Install NPM dependencies
        run: npm ci
      - name: Generate Go dependencies
        run: go generate ./...
      - name: Check Go formatting
        run: |
          go fmt ./...
          git diff --exit-code
      - name: Run Go tests
        run: go test -v ./...
